language: php

php:
  - 7.2
  - 7.3

before_script:
  - composer self-update
  - composer install
  - if [ $TRAVIS_PHP_VERSION == '7.3' ]; then pear install pear/PHP_CodeSniffer; fi
  - if [ $TRAVIS_PHP_VERSION == '7.3' ]; then phpenv rehash; fi

script:
  - if [ $TRAVIS_PHP_VERSION == '7.3' ]; then phpcs src/; fi
  - phpunit --coverage-text
  
