language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7.0

before_script:
  - composer self-update
  - composer install
  - if [ $TRAVIS_PHP_VERSION == '5.6' ]; then pyrus install pear/PHP_CodeSniffer; fi
  - if [ $TRAVIS_PHP_VERSION == '5.6' ]; then phpenv rehash; fi

script:
  - if [ $TRAVIS_PHP_VERSION == '5.6' ]; then phpcs --standard=psr2 src/; fi
  - phpunit --coverage-text
  
